# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MNWeibo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MNWeibo
pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod "pop"
pod "SwiftyJSON"

  target 'MNWeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MNWeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
